### ISSUE TITLE
Failing with "Cannot find pwsh in PATH"

### ISSUE THREAD

**Issue by ms609** [egor-tensin/setup-cygwin#12]
I'm running cygwin/cygwin-install-action@v4 from a Windows runner, using `act pull_request -j build-windows -P windows-latest=-self-hosted -s GITHUB_TOKEN="<...>"`

I see
```
[Build and test/build-windows] ⭐ Run Main Set up Cygwin
[Build and test/build-windows] ⭐ Run Main New-Variable os -Value ('windows') -Option Constant
New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

if (!$windows_host) {
    throw "Sorry, installing Cygwin is unsupported on $os"
}
| Cannot find: pwsh in PATH
[Build and test/build-windows]   ❌  Failure - Main New-Variable os -Value ('windows') -Option Constant
New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

if (!$windows_host) {
    throw "Sorry, installing Cygwin is unsupported on $os"
}
[Build and test/build-windows] Cannot find: pwsh in PATH
[Build and test/build-windows]   ❌  Failure - Main Set up Cygwin
[Build and test/build-windows] Cannot find: pwsh in PATH
```

Is there something I need to do to configure powershell?

Here's the top of my action.yml script:

```yaml
name: Build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
    - "*"


jobs:
  build-windows:
    runs-on: windows-latest
    env:
      SHELLOPTS: igncr
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login '{0}'
    
    steps:
    - name: Use safe line endings
      run: git config --global core.autocrlf input
      shell: cmd
      
    - uses: actions/checkout@v4
        
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        platform: x86_64
        packages: cmake #cmake-debuginfo cmake-doc cmake-gui mingw64-x86_64-gcc-core mingw64-x86_64-gcc-g++ git make python3
    
    - name: Declare success
      run: echo SUCCESS!
      shell: cmd
```

### Full output:
```
time="2024-07-11T21:05:17+01:00" level=warning msg="Couldn't get a valid docker connection: no DOCKER_HOST and an invalid container socket ''"
[Build and test/build-windows]   ☁  git clone 'https://github.com/egor-tensin/setup-cygwin' # ref=v4
[Build and test/build-windows] ⭐ Run Pre Set up Cygwin
[Build and test/build-windows]   ✅  Success - Pre Set up Cygwin
[Build and test/build-windows]   ☁  git clone 'https://github.com/egor-tensin/setup-mingw' # ref=v2
[Build and test/build-windows] ⭐ Run Pre Set up MinGW
[Build and test/build-windows]   ✅  Success - Pre Set up MinGW
[Build and test/build-windows]   ☁  git clone 'https://github.com/actions/cache' # ref=v2
[Build and test/build-windows]   ☁  git clone 'https://github.com/egor-tensin/build-boost' # ref=v1
[Build and test/build-windows] ⭐ Run Pre Build Boost
[Build and test/build-windows]   ✅  Success - Pre Build Boost
[Build and test/build-windows]   ☁  git clone 'https://github.com/threeal/cmake-action' # ref=main
[Build and test/build-windows]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Build and test/build-windows]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Build and test/build-windows] ⭐ Run Main Use safe line endings
[Build and test/build-windows]   ✅  Success - Main Use safe line endings
[Build and test/build-windows] ⭐ Run Main actions/checkout@v4
[Build and test/build-windows]   ✅  Success - Main actions/checkout@v4
[Build and test/build-windows] ⭐ Run Main Set up Cygwin
[Build and test/build-windows] ⭐ Run Main New-Variable os -Value ('windows') -Option Constant
New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

if (!$windows_host) {
    throw "Sorry, installing Cygwin is unsupported on $os"
}
| Cannot find: pwsh in PATH
[Build and test/build-windows]   ❌  Failure - Main New-Variable os -Value ('windows') -Option Constant
New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

if (!$windows_host) {
    throw "Sorry, installing Cygwin is unsupported on $os"
}
[Build and test/build-windows] Cannot find: pwsh in PATH
[Build and test/build-windows]   ❌  Failure - Main Set up Cygwin
[Build and test/build-windows] Cannot find: pwsh in PATH
[Build and test/build-windows] ⭐ Run Main Upload test files if they failed
[Build and test/build-windows]   💬  ::debug::followSymbolicLinks 'true'
[Build and test/build-windows]   💬  ::debug::implicitDescendants 'true'
[Build and test/build-windows]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Build and test/build-windows]   💬  ::debug::followSymbolicLinks 'true'
[Build and test/build-windows]   💬  ::debug::implicitDescendants 'true'
[Build and test/build-windows]   💬  ::debug::matchDirectories 'true'
[Build and test/build-windows]   💬  ::debug::omitBrokenSymbolicLinks 'true'
```
