### ISSUE TITLE
Feature request: Add cache

### ISSUE THREAD

**Issue by Endle** [egor-tensin/setup-cygwin#6]
If we cache cygwin packages, we can speed up CI process and save bandwidth for kernel.org
I tried https://github.com/Endle/wine-mono/blob/940e19c2abbc576f597e924270812721638b8eb1/.github/workflows/c-cpp.yml#L13 but t didn't work
```
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
          echo "::set-output name=time::$(/bin/date -u "+%H%M%S")"
        shell: bash
      - name: Cache Cygwin
        uses: actions/cache@v2
        env:
          cache-name: cache-cygwin-packages
        with:
          path: /cygdrive/c/tools/cygwin/packages
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-${{ steps.get-date.outputs.time }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-
            ${{ runner.os }}-${{ env.cache-name }}-
```
